import type { KbSectionSlug } from './knowledgeBase';

export interface RelatedLink {
  title: string;
  href: string;
}

export interface RoadmapPhase {
  number: number;
  title: string;
  section?: KbSectionSlug;
  objective: string;
  learn: string[];
  order: string[];
  tools: string[];
  skills: string[];
  completion: string[];
  related: RelatedLink[];
}

export const roadmapPhases: RoadmapPhase[] = [
  {
    number: 0,
    title: 'Foundations',
    section: 'foundations',
    objective:
      'Build the networking and operating-system fundamentals every penetration tester relies on, and set up an isolated lab you control.',
    learn: [
      'TCP/IP and the OSI model',
      'IPv4 addressing, subnetting, and CIDR',
      'DNS: how names resolve and which records exist',
      'HTTP: requests, responses, methods, status codes, headers, cookies',
      'Linux fundamentals: filesystem, permissions, users and groups, processes',
      'Bash essentials for moving around and scripting',
      'Windows basics: services, registry, users and groups',
      'Lab setup: attack machine, target VMs, isolated networking',
    ],
    order: [
      'Networking: TCP/IP, then subnetting, then DNS, then HTTP',
      'Linux: filesystem, permissions, processes, then bash',
      'Windows: services, registry, users and groups',
      'Build your lab and take a baseline snapshot',
    ],
    tools: ['bash', 'curl', 'ssh', 'wireshark', 'VirtualBox or VMware'],
    skills: [
      'Navigate Linux comfortably from the command line',
      'Read and change file permissions',
      'Inspect network configuration and live connections',
      'Intercept and read basic HTTP traffic',
      'Set up, snapshot, and revert an isolated lab',
    ],
    completion: [
      'I can explain the TCP three-way handshake',
      'I can subnet a /24 by hand',
      'I can explain how DNS resolution works',
      'I can read an HTTP request and response',
      'I am comfortable in a Linux terminal',
      'I understand Linux file permissions',
      'I know what a Windows service and the registry are',
      'My lab is isolated from my main network',
      'I can snapshot and restore my lab VMs',
      'I have a note-taking workflow in place',
    ],
    related: [{ title: 'Foundations guides', href: '/guides/foundations' }],
  },
  {
    number: 1,
    title: 'Information Gathering & Enumeration',
    section: 'info-gathering',
    objective:
      'Collect the maximum amount of information about the target with the smallest possible footprint, then prioritize what to investigate.',
    learn: [
      'Passive vs active reconnaissance',
      'DNS enumeration: dig, nslookup, zone transfers',
      'Subdomain and asset discovery',
      'Host discovery: ping sweeps and ARP scanning',
      'Netdiscover and basic network mapping',
      'Target prioritization based on exposed services',
      'Organized note-taking of everything discovered',
    ],
    order: [
      'Passive recon and OSINT',
      'DNS enumeration',
      'Host discovery on the target network',
      'Map the network and note every asset',
      'Prioritize targets by exposed attack surface',
    ],
    tools: ['dig', 'nslookup', 'whois', 'netdiscover', 'arp-scan', 'fping'],
    skills: [
      'Work passively before touching the target',
      'Enumerate DNS records and subdomains',
      'Discover live hosts on a local network',
      'Build a target inventory you can reference later',
      'Decide which hosts to enumerate first',
    ],
    completion: [
      'I can explain the difference between passive and active recon',
      'I can enumerate DNS records with dig',
      'I can discover live hosts with a ping sweep',
      'I can map a local network with netdiscover',
      'I record every finding in my notes',
      'I can justify which target to attack first',
    ],
    related: [
      { title: 'Information gathering guides', href: '/guides/info-gathering' },
      { title: 'Initial foothold playbook', href: '/playbooks' },
    ],
  },
  {
    number: 2,
    title: 'Network & Service Enumeration',
    section: 'info-gathering',
    objective:
      'Identify every open port and running service on the target, then determine what each service exposes to an attacker.',
    learn: [
      'TCP scan types and what each one tells you',
      'Nmap methodology: quick scans, full scans, version detection',
      'Default scripts and the Nmap Scripting Engine (NSE)',
      'Service fingerprinting and banner grabbing',
      'UDP scanning and why it is slow',
      'Mapping open ports to an attack surface',
    ],
    order: [
      'Quick scan for a fast overview',
      'Full TCP port scan',
      'Version detection and default scripts on open ports',
      'Banner grab unusual services manually',
      'UDP scan where the assessment warrants it',
      'Document every service with its version',
    ],
    tools: ['nmap', 'masscan', 'netcat', 'ncat', 'smbclient', 'rpcclient'],
    skills: [
      'Plan a scan order that balances speed and coverage',
      'Run quick and full TCP scans correctly',
      'Detect service versions and infer operating systems',
      'Use targeted NSE scripts',
      'Recognize which services deserve deeper enumeration',
    ],
    completion: [
      'I can run a quick TCP scan',
      'I can run a full TCP port scan',
      'I can enumerate versions and OS with -sC -sV',
      'I can use a targeted NSE script',
      'I can list the attack surface implied by open ports',
      'I record every open port in my notes',
    ],
    related: [{ title: 'Information gathering guides', href: '/guides/info-gathering' }],
  },
  {
    number: 3,
    title: 'Web Application Fundamentals',
    section: 'web',
    objective:
      'Understand how web applications work and map their attack surface before testing any specific vulnerability.',
    learn: [
      'HTTP request and response anatomy and state',
      'Sessions, cookies, and authentication concepts',
      'Content and directory discovery: gobuster, feroxbuster, ffuf',
      'Technology and version fingerprinting',
      'Burp Suite proxy workflow: intercept, modify, replay',
      'Parameter discovery and manipulation',
      'Authorization and access control concepts',
      'Overview of common web vulnerabilities',
    ],
    order: [
      'Load the app and observe its behavior',
      'Fingerprint the technology stack',
      'Map the app: endpoints, parameters, functionality',
      'Run content discovery',
      'Work through authentication and access control',
      'Probe each parameter for injection points',
    ],
    tools: ['Burp Suite', 'gobuster', 'feroxbuster', 'ffuf', 'nikto', 'curl'],
    skills: [
      'Intercept and modify requests in Burp',
      'Discover hidden directories and files',
      'Identify the stack powering an application',
      'Find parameters and understand what they control',
      'Test authentication and authorization behavior',
    ],
    completion: [
      'I can walk a request through Burp from interception to replay',
      'I can enumerate directories with a fuzzer',
      'I can identify a web technology stack',
      'I can map an application endpoint by endpoint',
      'I can manipulate parameters and observe responses',
      'I document the full attack surface',
    ],
    related: [
      { title: 'Web security guides', href: '/guides/web' },
      { title: 'Web enumeration playbook', href: '/playbooks' },
    ],
  },
  {
    number: 4,
    title: 'Exploitation',
    section: 'exploitation',
    objective:
      'Turn validated findings into access, and know when to automate and when to work manually.',
    learn: [
      'Validating a vulnerability before exploiting it',
      'Metasploit: search, select, configure, and run a module',
      'Payload concepts: reverse vs bind, stageless vs staged',
      'Generating payloads with msfvenom',
      'Setting up listeners and managing sessions',
      'Netcat reverse and bind shells',
      'Stabilizing an interactive shell',
      'Manual exploitation and searchsploit',
    ],
    order: [
      'Validate the finding manually',
      'Decide manual vs automated approach',
      'Pick a payload that fits the target OS and network',
      'Set up a listener before firing the exploit',
      'Get the shell and stabilize it',
      'Verify access and document it',
    ],
    tools: ['metasploit', 'msfvenom', 'netcat', 'ncat', 'searchsploit', 'python3'],
    skills: [
      'Confirm a vulnerability is real before acting on it',
      'Search and configure Metasploit modules',
      'Choose an appropriate payload',
      'Receive a reverse shell and upgrade it',
      'Document the full exploitation path',
    ],
    completion: [
      'I can validate a finding manually',
      'I can search and configure a Metasploit module',
      'I can generate a payload with msfvenom',
      'I can catch a reverse shell with netcat',
      'I can upgrade a shell to a stable interactive session',
      'I can document the exploitation path from finding to access',
    ],
    related: [
      { title: 'Exploitation guides', href: '/guides/exploitation' },
      { title: 'Initial foothold playbook', href: '/playbooks' },
    ],
  },
  {
    number: 5,
    title: 'Linux Privilege Escalation',
    section: 'linux-privesc',
    objective:
      'Systematically raise privileges on Linux from an unprivileged shell to root.',
    learn: [
      'Linux enumeration methodology: users, groups, files, sudo',
      'sudo configuration and what you can run',
      'SUID and SGID binaries',
      'Linux capabilities',
      'Writable files and directories',
      'Cron jobs and scheduled tasks',
      'PATH-related issues',
      'Credentials, SSH keys, and configuration files',
      'Services running as privileged users',
      'Kernel vulnerability identification',
      'LinPEAS and manual enumeration',
    ],
    order: [
      'Run manual enumeration first',
      'Correlate what you find with LinPEAS output',
      'Test each interesting lead in order of likelihood',
      'Validate the escalation in a controlled way',
      'Document exactly how you escalated',
    ],
    tools: ['linpeas', 'sudo', 'find', 'getcap', 'pspy', 'linux-exploit-suggester'],
    skills: [
      'Enumerate a Linux host by hand',
      'Interpret LinPEAS output and filter noise',
      'Recognize an escalation path from an enumeration lead',
      'Explain the root cause of each escalation',
    ],
    completion: [
      'I can enumerate users, groups, and files',
      'I can inspect sudo permissions',
      'I can find SUID binaries and identify interesting ones',
      'I can check capabilities',
      'I can find writable files and cron jobs',
      'I can identify credentials and SSH keys on disk',
      'I can escalate to root in an authorized lab',
      'I document the escalation path',
    ],
    related: [
      { title: 'Linux priv esc guides', href: '/guides/linux-privesc' },
      { title: 'Linux priv esc playbook', href: '/playbooks' },
    ],
  },
  {
    number: 6,
    title: 'Windows Privilege Escalation',
    section: 'windows-privesc',
    objective:
      'Systematically raise privileges on Windows from an unprivileged shell to an administrative user.',
    learn: [
      'Windows enumeration methodology with PowerShell',
      'Services and their configuration',
      'Weak service permissions and unquoted service paths',
      'Scheduled tasks',
      'Stored credentials: files, registry, autologon',
      'Registry-based privilege escalation paths',
      'Token and impersonation concepts',
      'Common Windows escalation paths',
      'WinPEAS and manual enumeration',
    ],
    order: [
      'Enumerate manually with PowerShell',
      'Correlate findings with WinPEAS output',
      'Test each lead in order of likelihood',
      'Validate the escalation in a controlled way',
      'Document exactly how you escalated',
    ],
    tools: ['winpeas', 'PowerShell', 'whoami', 'sc', 'reg', 'accesschk'],
    skills: [
      'Enumerate a Windows host from a shell',
      'Inspect services and their permissions',
      'Read scheduled tasks and registry keys',
      'Interpret WinPEAS output and filter noise',
      'Explain the root cause of each escalation',
    ],
    completion: [
      'I can enumerate users, groups, and privileges',
      'I can inspect service configuration and permissions',
      'I can find scheduled tasks and stored credentials',
      'I can explain token and impersonation concepts',
      'I can escalate to an administrative user in an authorized lab',
      'I document the escalation path',
    ],
    related: [
      { title: 'Windows priv esc guides', href: '/guides/windows-privesc' },
      { title: 'Windows priv esc playbook', href: '/playbooks' },
    ],
  },
  {
    number: 7,
    title: 'Active Directory',
    section: 'active-directory',
    objective:
      'Understand the Active Directory environment, enumerate it thoroughly, and apply the core attack concepts used in modern assessments.',
    learn: [
      'Active Directory fundamentals: domains, users, groups, computers',
      'Organizational Units and Group Policy concepts',
      'Domain Controllers and their role',
      'Domain trust concepts',
      'AD enumeration methodology',
      'BloodHound and SharpHound',
      'NetExec, enum4linux-ng, LDAP, and SMB enumeration',
      'Kerberoasting and AS-REP roasting',
      'Pass-the-Hash and Pass-the-Ticket',
      'LLMNR and NBT-NS poisoning with Responder',
      'Credential discovery and reuse',
      'Windows authentication concepts',
    ],
    order: [
      'Learn how authentication works in Windows',
      'Enumerate the domain from an unauthenticated position',
      'Gain a foothold and enumerate authenticated',
      'Collect data for BloodHound',
      'Apply attack concepts in order of least noise first',
      'Move toward the highest-value targets',
    ],
    tools: ['BloodHound', 'SharpHound', 'NetExec', 'enum4linux-ng', 'ldapsearch', 'Responder', 'PowerShell'],
    skills: [
      'Enumerate a domain with modern tooling',
      'Interpret BloodHound paths',
      'Understand when Kerberoasting and AS-REP apply',
      'Use Pass-the-Hash and Pass-the-Ticket correctly',
      'Explain the Windows authentication flow',
    ],
    completion: [
      'I can explain the core AD objects and their relationships',
      'I can enumerate users, groups, and computers',
      'I can collect and analyze BloodHound data',
      'I understand Kerberoasting and AS-REP roasting',
      'I can use Pass-the-Hash and Pass-the-Ticket',
      'I understand LLMNR poisoning and when it works',
      'I can document an AD attack path end to end',
    ],
    related: [
      { title: 'Active Directory guides', href: '/guides/active-directory' },
      { title: 'AD enumeration playbook', href: '/playbooks' },
      { title: 'Lateral movement guides', href: '/guides/lateral-movement' },
    ],
  },
  {
    number: 8,
    title: 'Lateral Movement',
    section: 'lateral-movement',
    objective:
      'Move across the network once you hold credentials or sessions, and decide which technique fits each situation.',
    learn: [
      'Credential reuse across the environment',
      'SMB, WinRM, and RDP as movement channels',
      'PsExec-style, WMI, and remote PowerShell concepts',
      'Pass-the-Hash and Pass-the-Ticket in practice',
      'Identifying the next target',
      'Deciding when to move laterally vs pivot',
    ],
    order: [
      'Inventory what credentials you hold',
      'Map where those credentials are valid',
      'Pick the quietest channel that works',
      'Test access on the next target',
      'Repeat until you reach the goal',
    ],
    tools: ['NetExec', 'evil-winrm', 'impacket', 'wmiexec', 'psexec', 'PowerShell'],
    skills: [
      'Test credentials against many hosts at once',
      'Choose between SMB, WinRM, and other channels',
      'Use Pass-the-Hash and Pass-the-Ticket',
      'Explain when to move laterally and when to pivot',
    ],
    completion: [
      'I can test credentials across a network',
      'I can move via SMB and WinRM',
      'I understand Pass-the-Hash and Pass-the-Ticket',
      'I can decide which movement channel fits the situation',
      'I document every hop in the movement path',
    ],
    related: [
      { title: 'Lateral movement guides', href: '/guides/lateral-movement' },
      { title: 'Lateral movement playbook', href: '/playbooks' },
      { title: 'Pivoting guides', href: '/guides/pivoting' },
    ],
  },
  {
    number: 9,
    title: 'Pivoting & Port Forwarding',
    section: 'pivoting',
    objective:
      'Reach networks that are not directly accessible by routing traffic through compromised hosts.',
    learn: [
      'What pivoting is and how segmented networks work',
      'Identifying internal networks from a foothold',
      'Route discovery from the compromised host',
      'SOCKS proxies and proxychains',
      'SSH local, remote, and dynamic port forwarding',
      'Chisel for firewall-friendly tunneling',
      'Ligolo-ng for agent-based pivoting',
      'Plink on Windows hosts',
      'Metasploit routing and port forwarding',
    ],
    order: [
      'Map the networks the foothold can reach',
      'Choose the tunneling technique that fits the path',
      'Establish the tunnel',
      'Route your tools through it',
      'Enumerate the internal target',
    ],
    tools: ['ssh', 'proxychains', 'chisel', 'ligolo-ng', 'plink', 'metasploit'],
    skills: [
      'Discover routes from a compromised host',
      'Forward a single port with SSH',
      'Set up a dynamic SOCKS proxy',
      'Use Chisel and Ligolo-ng for restricted paths',
      'Troubleshoot tunnel failures',
    ],
    completion: [
      'I can discover internal networks from a foothold',
      'I can set up SSH local and dynamic forwarding',
      'I can route tools through proxychains',
      'I can use Chisel and Ligolo-ng in a lab',
      'I can reach an internal service through a pivot',
      'I document the full pivot path',
    ],
    related: [
      { title: 'Pivoting guides', href: '/guides/pivoting' },
      { title: 'Pivoting playbook', href: '/playbooks' },
    ],
  },
  {
    number: 10,
    title: 'PowerShell',
    section: 'powershell',
    objective:
      'Use PowerShell fluently for the enumeration and remote administration tasks you will actually need on Windows targets.',
    learn: [
      'Command execution and pipeline basics',
      'Enumeration of users, groups, processes, and services',
      'Network discovery with PowerShell',
      'Searching files and content',
      'Credential-related enumeration concepts',
      'Remote administration concepts',
      'The PowerShell syntax used in pentesting',
    ],
    order: [
      'Learn cmdlets and the pipeline',
      'Practice local enumeration',
      'Practice network discovery',
      'Practice remote administration in a lab',
    ],
    tools: ['PowerShell', 'PowerShell remoting'],
    skills: [
      'Enumerate a Windows host with PowerShell',
      'Find interesting files and credentials',
      'Query processes and services',
      'Use remote administration cmdlets in a lab',
    ],
    completion: [
      'I can enumerate users and groups in PowerShell',
      'I can list processes and services',
      'I can discover network configuration',
      'I can search the filesystem for interesting content',
      'I can use PowerShell remoting in a lab',
    ],
    related: [
      { title: 'PowerShell guides', href: '/guides/powershell' },
      { title: 'Windows enumeration playbook', href: '/playbooks' },
    ],
  },
  {
    number: 11,
    title: 'Post-Exploitation & Methodology',
    section: 'methodology',
    objective:
      'Integrate every phase into one repeatable process and handle post-exploitation responsibly: evidence, notes, and cleanup.',
    learn: [
      'Evidence collection as you work',
      'Post-exploitation enumeration loops',
      'Persistence concepts for authorized environments',
      'Cleanup and restoration after a test',
      'The full assessment methodology from recon to reporting',
      'Decision trees for common situations',
    ],
    order: [
      'Practice the methodology on a full lab machine',
      'Follow the evidence and note-taking discipline',
      'Work through the decision trees until they are second nature',
    ],
    tools: ['Your notes system', 'screenshots', 'the knowledge base'],
    skills: [
      'Run a complete assessment from start to finish',
      'Keep evidence organized as you go',
      'Decide the next action without guessing',
      'Clean up after yourself',
    ],
    completion: [
      'I can run a complete methodology without skipping phases',
      'I collect evidence for every important finding',
      'I use decision trees to pick my next action',
      'I know how to clean up after an engagement',
    ],
    related: [
      { title: 'Methodology guides', href: '/guides/methodology' },
      { title: 'Methodology', href: '/methodology' },
    ],
  },
  {
    number: 12,
    title: 'Reporting',
    section: 'reporting',
    objective:
      'Turn raw findings and evidence into a clear, professional report that technical and non-technical readers can act on.',
    learn: [
      'Evidence collection: screenshots, commands, and output',
      'Writing a vulnerability description',
      'Explaining impact and business risk',
      'Writing reproduction steps',
      'Providing actionable remediation',
      'Professional report structure',
    ],
    order: [
      'Collect evidence during the test',
      'Write findings while they are fresh',
      'Structure the report for different audiences',
      'Review against a checklist',
    ],
    tools: ['markdown', 'screenshots', 'report templates'],
    skills: [
      'Describe a finding clearly and reproducibly',
      'Explain risk without exaggerating',
      'Produce a professional report structure',
    ],
    completion: [
      'I can write a clear finding description',
      'I can explain impact and risk',
      'I can write reproduction steps',
      'I can suggest remediation for common issues',
      'I can structure a full report',
    ],
    related: [
      { title: 'Reporting guides', href: '/guides/reporting' },
      { title: 'Reporting', href: '/reporting' },
    ],
  },
  {
    number: 13,
    title: 'Final Revision',
    objective:
      'Consolidate everything: rework weak areas, drill the reference material, and practice under realistic conditions.',
    learn: [
      'Revisit cheat sheets and playbooks',
      'Re-run decision trees until they are automatic',
      'Redo labs from memory without looking at the walkthrough',
      'Focus practice on your weakest areas',
      'Build and use your personal notes as revision material',
    ],
    order: [
      'Identify weak areas from lab performance',
      'Rework each weak area with the relevant guides',
      'Drill cheat sheets and playbooks',
      'Redo complete lab machines from memory',
    ],
    tools: ['Cheat sheets', 'Playbooks', 'Lab tracker', 'My notes'],
    skills: [
      'Work through machines without a walkthrough',
      'Recall key commands and techniques quickly',
      'Self-assess honestly and close gaps',
    ],
    completion: [
      'I have reworked my weakest areas',
      'I can complete a lab machine from memory',
      'I can recall key commands without notes',
      'I have reviewed the cheat sheets',
      'I have practiced each decision tree',
    ],
    related: [
      { title: 'Cheat sheets', href: '/cheat-sheets' },
      { title: 'Playbooks', href: '/playbooks' },
      { title: 'Exam preparation', href: '/exam-prep' },
    ],
  },
  {
    number: 14,
    title: 'Exam Readiness',
    objective:
      'Prepare the environment, strategy, and mindset for exam day.',
    learn: [
      'Environment preparation and tool verification',
      'Time management across a long assessment',
      'Troubleshooting strategy when stuck',
      'Documentation habits under pressure',
      'Final readiness checklist',
    ],
    order: [
      'Verify your environment and tools',
      'Review time management and troubleshooting plans',
      'Run the readiness checklist',
      'Rest before exam day',
    ],
    tools: ['Cheat sheets', 'Decision trees', 'Lab tracker', 'Playbooks'],
    skills: [
      'Manage time across a long, multi-target assessment',
      'Recover quickly when stuck',
      'Keep evidence organized under pressure',
    ],
    completion: [
      'My environment and tools are verified',
      'I have a time management plan',
      'I have a troubleshooting plan for when I am stuck',
      'I have run the final readiness checklist',
      'I know the platform terms I must follow',
    ],
    related: [
      { title: 'Exam preparation', href: '/exam-prep' },
      { title: 'Practical insights', href: '/insights' },
      { title: 'Cheat sheets', href: '/cheat-sheets' },
    ],
  },
];
